/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicSubscriptionRouteImport } from './routes/(public)/subscription'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as privateAdminRouteRouteImport } from './routes/(private)/admin/route'
import { Route as privateWorkspaceIndexRouteImport } from './routes/(private)/workspace/index'
import { Route as privateUserIndexRouteImport } from './routes/(private)/user/index'
import { Route as privateAdminIndexRouteImport } from './routes/(private)/admin/index'
import { Route as privateAdminWorkspaceRouteImport } from './routes/(private)/admin/workspace'
import { Route as privateAdminUsersRouteImport } from './routes/(private)/admin/users'
import { Route as privateAdminMonitoringRouteRouteImport } from './routes/(private)/admin/monitoring/route'
import { Route as privateAdminSettingsIndexRouteImport } from './routes/(private)/admin/settings/index'
import { Route as privateAdminMonitoringIndexRouteImport } from './routes/(private)/admin/monitoring/index'
import { Route as privateAdminMonitoringSuspiciousActivitiesRouteImport } from './routes/(private)/admin/monitoring/suspicious-activities'
import { Route as privateAdminMonitoringSanctionsRouteImport } from './routes/(private)/admin/monitoring/sanctions'
import { Route as privateAdminMonitoringNotificationsRouteImport } from './routes/(private)/admin/monitoring/notifications'
import { Route as privateAdminMonitoringLogsRouteImport } from './routes/(private)/admin/monitoring/logs'
import { Route as privateAdminMonitoringAnnouncementsRouteImport } from './routes/(private)/admin/monitoring/announcements'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSubscriptionRoute = publicSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => publicRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/(auth)/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const privateAdminRouteRoute = privateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateWorkspaceIndexRoute = privateWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateUserIndexRoute = privateUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateAdminIndexRoute = privateAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateAdminRouteRoute,
} as any)
const privateAdminWorkspaceRoute = privateAdminWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => privateAdminRouteRoute,
} as any)
const privateAdminUsersRoute = privateAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => privateAdminRouteRoute,
} as any)
const privateAdminMonitoringRouteRoute =
  privateAdminMonitoringRouteRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => privateAdminRouteRoute,
  } as any)
const privateAdminSettingsIndexRoute =
  privateAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => privateAdminRouteRoute,
  } as any)
const privateAdminMonitoringIndexRoute =
  privateAdminMonitoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateAdminMonitoringRouteRoute,
  } as any)
const privateAdminMonitoringSuspiciousActivitiesRoute =
  privateAdminMonitoringSuspiciousActivitiesRouteImport.update({
    id: '/suspicious-activities',
    path: '/suspicious-activities',
    getParentRoute: () => privateAdminMonitoringRouteRoute,
  } as any)
const privateAdminMonitoringSanctionsRoute =
  privateAdminMonitoringSanctionsRouteImport.update({
    id: '/sanctions',
    path: '/sanctions',
    getParentRoute: () => privateAdminMonitoringRouteRoute,
  } as any)
const privateAdminMonitoringNotificationsRoute =
  privateAdminMonitoringNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => privateAdminMonitoringRouteRoute,
  } as any)
const privateAdminMonitoringLogsRoute =
  privateAdminMonitoringLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => privateAdminMonitoringRouteRoute,
  } as any)
const privateAdminMonitoringAnnouncementsRoute =
  privateAdminMonitoringAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => privateAdminMonitoringRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof privateAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/subscription': typeof publicSubscriptionRoute
  '/': typeof publicIndexRoute
  '/admin/monitoring': typeof privateAdminMonitoringRouteRouteWithChildren
  '/admin/users': typeof privateAdminUsersRoute
  '/admin/workspace': typeof privateAdminWorkspaceRoute
  '/admin/': typeof privateAdminIndexRoute
  '/user/': typeof privateUserIndexRoute
  '/workspace/': typeof privateWorkspaceIndexRoute
  '/admin/monitoring/announcements': typeof privateAdminMonitoringAnnouncementsRoute
  '/admin/monitoring/logs': typeof privateAdminMonitoringLogsRoute
  '/admin/monitoring/notifications': typeof privateAdminMonitoringNotificationsRoute
  '/admin/monitoring/sanctions': typeof privateAdminMonitoringSanctionsRoute
  '/admin/monitoring/suspicious-activities': typeof privateAdminMonitoringSuspiciousActivitiesRoute
  '/admin/monitoring/': typeof privateAdminMonitoringIndexRoute
  '/admin/settings/': typeof privateAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/subscription': typeof publicSubscriptionRoute
  '/': typeof publicIndexRoute
  '/admin/users': typeof privateAdminUsersRoute
  '/admin/workspace': typeof privateAdminWorkspaceRoute
  '/admin': typeof privateAdminIndexRoute
  '/user': typeof privateUserIndexRoute
  '/workspace': typeof privateWorkspaceIndexRoute
  '/admin/monitoring/announcements': typeof privateAdminMonitoringAnnouncementsRoute
  '/admin/monitoring/logs': typeof privateAdminMonitoringLogsRoute
  '/admin/monitoring/notifications': typeof privateAdminMonitoringNotificationsRoute
  '/admin/monitoring/sanctions': typeof privateAdminMonitoringSanctionsRoute
  '/admin/monitoring/suspicious-activities': typeof privateAdminMonitoringSuspiciousActivitiesRoute
  '/admin/monitoring': typeof privateAdminMonitoringIndexRoute
  '/admin/settings': typeof privateAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/admin': typeof privateAdminRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(public)/subscription': typeof publicSubscriptionRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/admin/monitoring': typeof privateAdminMonitoringRouteRouteWithChildren
  '/(private)/admin/users': typeof privateAdminUsersRoute
  '/(private)/admin/workspace': typeof privateAdminWorkspaceRoute
  '/(private)/admin/': typeof privateAdminIndexRoute
  '/(private)/user/': typeof privateUserIndexRoute
  '/(private)/workspace/': typeof privateWorkspaceIndexRoute
  '/(private)/admin/monitoring/announcements': typeof privateAdminMonitoringAnnouncementsRoute
  '/(private)/admin/monitoring/logs': typeof privateAdminMonitoringLogsRoute
  '/(private)/admin/monitoring/notifications': typeof privateAdminMonitoringNotificationsRoute
  '/(private)/admin/monitoring/sanctions': typeof privateAdminMonitoringSanctionsRoute
  '/(private)/admin/monitoring/suspicious-activities': typeof privateAdminMonitoringSuspiciousActivitiesRoute
  '/(private)/admin/monitoring/': typeof privateAdminMonitoringIndexRoute
  '/(private)/admin/settings/': typeof privateAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/verify-otp'
    | '/subscription'
    | '/'
    | '/admin/monitoring'
    | '/admin/users'
    | '/admin/workspace'
    | '/admin/'
    | '/user/'
    | '/workspace/'
    | '/admin/monitoring/announcements'
    | '/admin/monitoring/logs'
    | '/admin/monitoring/notifications'
    | '/admin/monitoring/sanctions'
    | '/admin/monitoring/suspicious-activities'
    | '/admin/monitoring/'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/verify-otp'
    | '/subscription'
    | '/'
    | '/admin/users'
    | '/admin/workspace'
    | '/admin'
    | '/user'
    | '/workspace'
    | '/admin/monitoring/announcements'
    | '/admin/monitoring/logs'
    | '/admin/monitoring/notifications'
    | '/admin/monitoring/sanctions'
    | '/admin/monitoring/suspicious-activities'
    | '/admin/monitoring'
    | '/admin/settings'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(private)/admin'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(auth)/verify-otp'
    | '/(public)/subscription'
    | '/(public)/'
    | '/(private)/admin/monitoring'
    | '/(private)/admin/users'
    | '/(private)/admin/workspace'
    | '/(private)/admin/'
    | '/(private)/user/'
    | '/(private)/workspace/'
    | '/(private)/admin/monitoring/announcements'
    | '/(private)/admin/monitoring/logs'
    | '/(private)/admin/monitoring/notifications'
    | '/(private)/admin/monitoring/sanctions'
    | '/(private)/admin/monitoring/suspicious-activities'
    | '/(private)/admin/monitoring/'
    | '/(private)/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/subscription': {
      id: '/(public)/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof publicSubscriptionRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/admin': {
      id: '/(private)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof privateAdminRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/workspace/': {
      id: '/(private)/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof privateWorkspaceIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/user/': {
      id: '/(private)/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof privateUserIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/admin/': {
      id: '/(private)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof privateAdminIndexRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
    '/(private)/admin/workspace': {
      id: '/(private)/admin/workspace'
      path: '/workspace'
      fullPath: '/admin/workspace'
      preLoaderRoute: typeof privateAdminWorkspaceRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
    '/(private)/admin/users': {
      id: '/(private)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof privateAdminUsersRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
    '/(private)/admin/monitoring': {
      id: '/(private)/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof privateAdminMonitoringRouteRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
    '/(private)/admin/settings/': {
      id: '/(private)/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof privateAdminSettingsIndexRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
    '/(private)/admin/monitoring/': {
      id: '/(private)/admin/monitoring/'
      path: '/'
      fullPath: '/admin/monitoring/'
      preLoaderRoute: typeof privateAdminMonitoringIndexRouteImport
      parentRoute: typeof privateAdminMonitoringRouteRoute
    }
    '/(private)/admin/monitoring/suspicious-activities': {
      id: '/(private)/admin/monitoring/suspicious-activities'
      path: '/suspicious-activities'
      fullPath: '/admin/monitoring/suspicious-activities'
      preLoaderRoute: typeof privateAdminMonitoringSuspiciousActivitiesRouteImport
      parentRoute: typeof privateAdminMonitoringRouteRoute
    }
    '/(private)/admin/monitoring/sanctions': {
      id: '/(private)/admin/monitoring/sanctions'
      path: '/sanctions'
      fullPath: '/admin/monitoring/sanctions'
      preLoaderRoute: typeof privateAdminMonitoringSanctionsRouteImport
      parentRoute: typeof privateAdminMonitoringRouteRoute
    }
    '/(private)/admin/monitoring/notifications': {
      id: '/(private)/admin/monitoring/notifications'
      path: '/notifications'
      fullPath: '/admin/monitoring/notifications'
      preLoaderRoute: typeof privateAdminMonitoringNotificationsRouteImport
      parentRoute: typeof privateAdminMonitoringRouteRoute
    }
    '/(private)/admin/monitoring/logs': {
      id: '/(private)/admin/monitoring/logs'
      path: '/logs'
      fullPath: '/admin/monitoring/logs'
      preLoaderRoute: typeof privateAdminMonitoringLogsRouteImport
      parentRoute: typeof privateAdminMonitoringRouteRoute
    }
    '/(private)/admin/monitoring/announcements': {
      id: '/(private)/admin/monitoring/announcements'
      path: '/announcements'
      fullPath: '/admin/monitoring/announcements'
      preLoaderRoute: typeof privateAdminMonitoringAnnouncementsRouteImport
      parentRoute: typeof privateAdminMonitoringRouteRoute
    }
  }
}

interface privateAdminMonitoringRouteRouteChildren {
  privateAdminMonitoringAnnouncementsRoute: typeof privateAdminMonitoringAnnouncementsRoute
  privateAdminMonitoringLogsRoute: typeof privateAdminMonitoringLogsRoute
  privateAdminMonitoringNotificationsRoute: typeof privateAdminMonitoringNotificationsRoute
  privateAdminMonitoringSanctionsRoute: typeof privateAdminMonitoringSanctionsRoute
  privateAdminMonitoringSuspiciousActivitiesRoute: typeof privateAdminMonitoringSuspiciousActivitiesRoute
  privateAdminMonitoringIndexRoute: typeof privateAdminMonitoringIndexRoute
}

const privateAdminMonitoringRouteRouteChildren: privateAdminMonitoringRouteRouteChildren =
  {
    privateAdminMonitoringAnnouncementsRoute:
      privateAdminMonitoringAnnouncementsRoute,
    privateAdminMonitoringLogsRoute: privateAdminMonitoringLogsRoute,
    privateAdminMonitoringNotificationsRoute:
      privateAdminMonitoringNotificationsRoute,
    privateAdminMonitoringSanctionsRoute: privateAdminMonitoringSanctionsRoute,
    privateAdminMonitoringSuspiciousActivitiesRoute:
      privateAdminMonitoringSuspiciousActivitiesRoute,
    privateAdminMonitoringIndexRoute: privateAdminMonitoringIndexRoute,
  }

const privateAdminMonitoringRouteRouteWithChildren =
  privateAdminMonitoringRouteRoute._addFileChildren(
    privateAdminMonitoringRouteRouteChildren,
  )

interface privateAdminRouteRouteChildren {
  privateAdminMonitoringRouteRoute: typeof privateAdminMonitoringRouteRouteWithChildren
  privateAdminUsersRoute: typeof privateAdminUsersRoute
  privateAdminWorkspaceRoute: typeof privateAdminWorkspaceRoute
  privateAdminIndexRoute: typeof privateAdminIndexRoute
  privateAdminSettingsIndexRoute: typeof privateAdminSettingsIndexRoute
}

const privateAdminRouteRouteChildren: privateAdminRouteRouteChildren = {
  privateAdminMonitoringRouteRoute:
    privateAdminMonitoringRouteRouteWithChildren,
  privateAdminUsersRoute: privateAdminUsersRoute,
  privateAdminWorkspaceRoute: privateAdminWorkspaceRoute,
  privateAdminIndexRoute: privateAdminIndexRoute,
  privateAdminSettingsIndexRoute: privateAdminSettingsIndexRoute,
}

const privateAdminRouteRouteWithChildren =
  privateAdminRouteRoute._addFileChildren(privateAdminRouteRouteChildren)

interface privateRouteRouteChildren {
  privateAdminRouteRoute: typeof privateAdminRouteRouteWithChildren
  privateUserIndexRoute: typeof privateUserIndexRoute
  privateWorkspaceIndexRoute: typeof privateWorkspaceIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateAdminRouteRoute: privateAdminRouteRouteWithChildren,
  privateUserIndexRoute: privateUserIndexRoute,
  privateWorkspaceIndexRoute: privateWorkspaceIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicSubscriptionRoute: typeof publicSubscriptionRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicSubscriptionRoute: publicSubscriptionRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
