/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicSubscriptionRouteImport } from './routes/(public)/subscription'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as privateAdminRouteRouteImport } from './routes/(private)/admin/route'
import { Route as privateWorkspaceIndexRouteImport } from './routes/(private)/workspace/index'
import { Route as privateUserIndexRouteImport } from './routes/(private)/user/index'
import { Route as privateAdminIndexRouteImport } from './routes/(private)/admin/index'
import { Route as privateAdminUsersRouteImport } from './routes/(private)/admin/users'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSubscriptionRoute = publicSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => publicRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/(auth)/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const privateAdminRouteRoute = privateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateWorkspaceIndexRoute = privateWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateUserIndexRoute = privateUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateAdminIndexRoute = privateAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateAdminRouteRoute,
} as any)
const privateAdminUsersRoute = privateAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => privateAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof privateAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/subscription': typeof publicSubscriptionRoute
  '/': typeof publicIndexRoute
  '/admin/users': typeof privateAdminUsersRoute
  '/admin/': typeof privateAdminIndexRoute
  '/user/': typeof privateUserIndexRoute
  '/workspace/': typeof privateWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/subscription': typeof publicSubscriptionRoute
  '/': typeof publicIndexRoute
  '/admin/users': typeof privateAdminUsersRoute
  '/admin': typeof privateAdminIndexRoute
  '/user': typeof privateUserIndexRoute
  '/workspace': typeof privateWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/admin': typeof privateAdminRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(public)/subscription': typeof publicSubscriptionRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/admin/users': typeof privateAdminUsersRoute
  '/(private)/admin/': typeof privateAdminIndexRoute
  '/(private)/user/': typeof privateUserIndexRoute
  '/(private)/workspace/': typeof privateWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-otp'
    | '/subscription'
    | '/'
    | '/admin/users'
    | '/admin/'
    | '/user/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-otp'
    | '/subscription'
    | '/'
    | '/admin/users'
    | '/admin'
    | '/user'
    | '/workspace'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(private)/admin'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-otp'
    | '/(public)/subscription'
    | '/(public)/'
    | '/(private)/admin/users'
    | '/(private)/admin/'
    | '/(private)/user/'
    | '/(private)/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/subscription': {
      id: '/(public)/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof publicSubscriptionRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/admin': {
      id: '/(private)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof privateAdminRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/workspace/': {
      id: '/(private)/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof privateWorkspaceIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/user/': {
      id: '/(private)/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof privateUserIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/admin/': {
      id: '/(private)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof privateAdminIndexRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
    '/(private)/admin/users': {
      id: '/(private)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof privateAdminUsersRouteImport
      parentRoute: typeof privateAdminRouteRoute
    }
  }
}

interface privateAdminRouteRouteChildren {
  privateAdminUsersRoute: typeof privateAdminUsersRoute
  privateAdminIndexRoute: typeof privateAdminIndexRoute
}

const privateAdminRouteRouteChildren: privateAdminRouteRouteChildren = {
  privateAdminUsersRoute: privateAdminUsersRoute,
  privateAdminIndexRoute: privateAdminIndexRoute,
}

const privateAdminRouteRouteWithChildren =
  privateAdminRouteRoute._addFileChildren(privateAdminRouteRouteChildren)

interface privateRouteRouteChildren {
  privateAdminRouteRoute: typeof privateAdminRouteRouteWithChildren
  privateUserIndexRoute: typeof privateUserIndexRoute
  privateWorkspaceIndexRoute: typeof privateWorkspaceIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateAdminRouteRoute: privateAdminRouteRouteWithChildren,
  privateUserIndexRoute: privateUserIndexRoute,
  privateWorkspaceIndexRoute: privateWorkspaceIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicSubscriptionRoute: typeof publicSubscriptionRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicSubscriptionRoute: publicSubscriptionRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
